spring:
  datasource: #配置数据源信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #显示sql语句
  jackson:
    default-property-inclusion: non_null #对象转换成json时，空属性直接忽略（作用域：全局）
server:
  servlet-path: /sell

wechat:
  appID: wxde9ab4be7455013b
  appsecret: 7e03e87680ce6852a8ac84f6ad43233a

#logging:
#  pattern:
#    console: "%d - %msg%n" #写日志的格式
#  level: debug
##  path: D:\sell #把日志写到哪个目录下
#  file: D:\sell\sell.log #指定日志写到哪里